"""initial setup

Revision ID: 0a42661efeea
Revises: 
Create Date: 2020-11-29 15:46:43.778564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42661efeea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('display_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Structures_creation_date'), 'Structures', ['creation_date'], unique=False)
    op.create_index(op.f('ix_Structures_last_update_date'), 'Structures', ['last_update_date'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=32), nullable=False),
    sa.Column('lastName', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('administrator', sa.Boolean(), nullable=True),
    sa.Column('privileged', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verify_code', sa.String(length=32), nullable=False),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expiration', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_creation_date'), 'Users', ['creation_date'], unique=False)
    op.create_table('Applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['Structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['Structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Modifications')
    op.drop_table('Applications')
    op.drop_index(op.f('ix_Users_creation_date'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Structures_last_update_date'), table_name='Structures')
    op.drop_index(op.f('ix_Structures_creation_date'), table_name='Structures')
    op.drop_table('Structures')
    # ### end Alembic commands ###
