"""Initial setup

Revision ID: 1775295ba47f
Revises: 
Create Date: 2020-11-23 21:27:44.030243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1775295ba47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('display_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structures_creation_date'), 'structures', ['creation_date'], unique=False)
    op.create_index(op.f('ix_structures_last_update_date'), 'structures', ['last_update_date'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modifications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_structures_last_update_date'), table_name='structures')
    op.drop_index(op.f('ix_structures_creation_date'), table_name='structures')
    op.drop_table('structures')
    # ### end Alembic commands ###
